/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "driver/stm.h"
#include "driver/imu.h"
#include "driver/asclin.h"
#include "driver/Etc.h"
#include "driver/ToF.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;


TestCnt stTestCnt;


// Task scheduling related
void AppScheduling(void);
void AppTask1ms(void);
void AppTask10ms(void);
void AppTask100ms(void);
void AppTask1000ms(void);

int distance = 0;
int prev_distance = -1;
int flag50ms = 0;

int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    /* Initialize */
    initShellInterface();                   //Debug_init
    Driver_Stm_Init();                      //Scheduling_init
    ToF_Init();                             //ToF_init
    init_I2C_module();                      //I2C_init
    init_mpu9250_registers();               //mpu92500_registers_init
    init_ak8963_registers();                //ak8963_registers_init
    delay_ms(500);
//    calibrate_gyro();                       //calibrate
//    delay_ms(1000);


    while(1)
    {
        AppScheduling();
    }
    return (1);
}


void AppTask1ms(void)
{
    stTestCnt.u32nuCnt1ms++;
}

void AppTask10ms(void)
{
    stTestCnt.u32nuCnt10ms++;
    flag50ms++;
    if(flag50ms ==5){
//        read_mpu9250_sensor_data();
//        print_mpu9250_sensor_data();
        flag50ms = 0;
//        sint16 mx, my, mz;
//        read_magnetometer_raw(&mx, &my, &mz);
//        print("MAG: X=%d Y=%d Z=%d\n\r", mx, my, mz);
//        if (distance >= 0)
//        {
//            // 새 거리 유효 → 저장 및 출력
//            prev_distance = distance;
//        }
//            // 유효하지 않아도 이전 값 출력
//            if (prev_distance >= 0)
//                print("Distance: %d cm\n\r", prev_distance);
//            else
//                print("Distance: -1 (no valid reading yet)\n\r");
    }
}

void AppTask100ms(void)
{
    stTestCnt.u32nuCnt100ms++;
    distance = data();
}

void AppTask1000ms(void)
{
    stTestCnt.u32nuCnt1000ms++;
    sint16 ax, ay, az;
    sint16 gx, gy, gz;
    sint16 mx, my, mz;
    read_accel_raw(&ax, &ay, &az);
    read_gyro_raw(&gx, &gy, &gz);
    read_magnetometer_raw(&mx, &my, &mz);
    print("Accel: X=%d Y=%d Z=%d\n\r", ax, ay, az);
    print("Gyro: X=%d Y=%d Z=%d\n\r", gx, gy, gz);
    print("MAG: X=%d Y=%d Z=%d\n\r", mx, my, mz);

//    if (distance >= 0)
//    {
//        // 새 거리 유효 → 저장 및 출력
//        prev_distance = distance;
//    }
//        // 유효하지 않아도 이전 값 출력
//        if (prev_distance >= 0)
//            print("Distance: %d cm\n\r", prev_distance);
//        else
//            print("Distance: -1 (no valid reading yet)\n\r");
}

void AppScheduling(void)
{
    if(stSchedulingInfo.u8nuScheduling1msFlag == 1u)
    {
        stSchedulingInfo.u8nuScheduling1msFlag = 0u;
        AppTask1ms();

        if(stSchedulingInfo.u8nuScheduling10msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling10msFlag = 0u;
            AppTask10ms();
        }

        if(stSchedulingInfo.u8nuScheduling100msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling100msFlag = 0u;
            AppTask100ms();
        }
        if(stSchedulingInfo.u8nuScheduling1000msFlag == 1u)
        {
            stSchedulingInfo.u8nuScheduling1000msFlag = 0u;
            AppTask1000ms();
        }
    }
}
