/**********************************************************************************************************************
 * \file SMU_IR_Alarm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "SMU_IR_Alarm.h"
#include "Ifx_Types.h"
#include "IfxSmu.h"
#include "IfxSrc.h"
#include "Bsp.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
//#include "IfxScuWdt.h"
//#include "IfxPort.h" // added
//#include "IfxScuWdt.h" // added
//#include "stdint.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define ISR_PRIORITY_SMU_INT0   10                      /* Define the SMU Service Request 0 interrupt priority  */
#define ISR_PRIORITY_SMU_INT1   9

#define PCn_2_IDX 19
#define P2_IDX 2
#define PCn_1_IDX 11
#define P1_IDX 1
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

/* Macro to define Interrupt Service Routine */
// 우선순위는 10이다. SW알람 0번이 발생했을 때 이 함수가 호출됨

IFX_INTERRUPT(ISR_SMU_Alarm, 0, ISR_PRIORITY_SMU_INT0);
IFX_INTERRUPT(ISR_SMU_Alarm1, 0, ISR_PRIORITY_SMU_INT1);
/* Interrupt Service Routine of SMU, gets triggered when the SMU Software Alarm 0 is triggered */
void ISR_SMU_Alarm(void)
{
    /* Command to enable the alarm clearing. This has to be done before clearing the status flag */
    IfxSmu_cmd(&MODULE_SMU, IfxSmu_Cmd_enableClearAlarmStatus, 0);
    IfxSmu_clearAlarm(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm0);    /* Clear alarm status flag                  */

    P10_OUT.U |= (0x1 << P2_IDX);
}
void ISR_SMU_Alarm1(void)
{
    /* Command to enable the alarm clearing. This has to be done before clearing the status flag */
    IfxSmu_cmd(&MODULE_SMU, IfxSmu_Cmd_enableClearAlarmStatus, 0);
    IfxSmu_clearAlarm(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm1);    /* Clear alarm status flag                  */

    P10_OUT.U |= (0x1 << P1_IDX);
}
void SMU_configuration(void)
{
    initLED();
    /* Enable the SMU register configuration by setting the CFGLCK field of the SMU_KEYS register to 0xBC */
    IfxSmu_unlock(&MODULE_SMU);

    /* Clear Safety ENDINIT protection for modification of the configuration registers */
    IfxScuWdt_clearSafetyEndinit(IfxScuWdt_getSafetyWatchdogPasswordInline());
    /* Set the IGCS0 field of SMU_AGC register to 1 to trigger SMU Interrupt Request 0 */
    MODULE_SMU.AGC.B.IGCS0 = 1;
    MODULE_SMU.AGC.B.IGCS1 = 2;
    /* Set Safety ENDINIT protection after modification of the configuration registers */
    IfxScuWdt_setSafetyEndinit(IfxScuWdt_getSafetyWatchdogPasswordInline());

    /* SMU alarm configuration: select Software Alarm 0 (alarm group 5) and send the interrupt request to the
     * interrupt system according to the Interrupt Generation Configuration Set 0 (IGCS0)
     */
    IfxSmu_setAlarmConfig(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm0, IfxSmu_AlarmConfig_interruptSet0);
    IfxSmu_setAlarmConfig(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm1, IfxSmu_AlarmConfig_interruptSet1); // a

    IfxSmu_lock(&MODULE_SMU);           /* After configuration, set a temporary lock of the SMU configuration   */


    /* Service request configuration */
    /* Get source pointer of SMU Service Request 0 in order to initialize and enable it */
    volatile Ifx_SRC_SRCR *src = &SRC_SMU0;
    IfxSrc_init(src, IfxSrc_Tos_cpu2, ISR_PRIORITY_SMU_INT0);
    IfxSrc_enable(src);

    // !!! 이 부분이 빠짐 -> SRC_SMU1을 설정하지 않아서 interruptSet1이 연결되지 않음
    volatile Ifx_SRC_SRCR *src1 = &SRC_SMU1;
    IfxSrc_init(src1, IfxSrc_Tos_cpu2, ISR_PRIORITY_SMU_INT1);
    IfxSrc_enable(src1);

    IfxSmu_cmd(&MODULE_SMU, IfxSmu_Cmd_start, 0);                   /* Start the SMU state machine (SSM)        */
}

/* This function triggers the Software Alarm 0 */
void trigger_SMU_alarm(void)
{
    IfxSmu_triggerAlarm(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm0);  /* Trigger Software Alarm 0                 */
}
void trigger_SMU_alarm1(void)
{
    IfxSmu_triggerAlarm(&MODULE_SMU, IfxSmu_Alarm_SoftwareAlarm1);  /* Trigger Software Alarm 1                 */
}
void initLED (void)
{
    P10_IOCR0.U &= ~(0x1F << PCn_2_IDX);
    P10_IOCR0.U |= 0x10 << PCn_2_IDX;

    P10_IOCR0.U &= ~(0x1F << PCn_1_IDX);
    P10_IOCR0.U |= 0x10 << PCn_1_IDX;
}
